### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'MutableMapping'

### ISSUE THREAD

**Issue by beingPurple** [FasterDecoding/Medusa#11]
WHen I run `python -m medusa.inference.cli --model FasterDecoding/medusa-vicuna-13b-v1.3', I get `AttributeError: module 'collections' has no attribute 'MutableMapping'`

Seems like a fastchat related issue?
Using WSL python 3.11.5 in a n anaconda environment

**Comment by leeyeehoo** [comment]
I searched it and seems like [python version issue](https://stackoverflow.com/a/71902541). It happens when your python >= 3.10.

**Comment by beingPurple** [comment]
ah thank you, I was overthinking it!
