### ISSUE TITLE
Is there any document that describes the Medusa inference details and theory?

### ISSUE THREAD

**Issue by YingHH1** [FasterDecoding/Medusa#13]
Hi there,

Thank you for the great work! I've read through the blog in https://sites.google.com/view/medusa-llm, and I found it useful to understand the broader picture of the method. However, I do find the implementation details to be quite challenging to comprehend. I was wondering if there is (or planning) a document that contains the underlying theory, such as these functions:
- generate_candidates
- tree_decoding
- evaluate_posterior
- update_inference_inputs

Many thanks!

**Comment by leeyeehoo** [comment]
Yes, I have the same thought! Will write a detailed document to explain this (estimated done by this week).

**Comment by leeyeehoo** [comment]
UPDATE: Preview is [here](https://github.com/FasterDecoding/Medusa/blob/sparse_tree/notebooks/medusa_introduction.ipynb)

**Comment by MeWannaSleep** [comment]
@leeyeehoo ,hi I've read medusa_configuration_explained.ipynb, but still don't understand why is medusa_attn_mask only used in the inference phase? Could you please elaborate on this ?

**Comment by leeyeehoo** [comment]
@MeWannaSleep Sorry, I didn't have a notification on. It is for tree attention. For training, we just train the heads to predict the future. If you want to further understand the training pipeline, see our training code.
