### ISSUE TITLE
[New feature] Fine-tune Medusa heads during SFT

### ISSUE THREAD

**Issue by ctlllll** [FasterDecoding/Medusa#36]

**Comment by santhosh97** [comment]
What does this exactly mean? Does this mean training all the parameters including the original model (unfreezing the original model) parameters + medusa heads from scratch)

**Comment by ctlllll** [comment]
Track:
I added initial support for Medusa to the popular fine-tuning codebase.
See commit: https://github.com/ctlllll/axolotl/commit/61fc938f431b59dc91d0327949dae48d9f65b053

**Comment by ctlllll** [comment]
Added in v1.0.
