### ISSUE TITLE
Benchmark results

### ISSUE THREAD

**Issue by JianbangZ** [FasterDecoding/Medusa#37]
(1) I think you mentioned you use MT Bench. Could you release the code to run MT Bench?
(2) Have you run other benchmarks listed on https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard?

**Comment by leeyeehoo** [comment]
Yes. I’ll release it soon.

**Comment by leeyeehoo** [comment]
Hi Jim, I updated `llm_judge`. Feel free to reopen if you have further questions or suggestions!

**Comment by forresti** [comment]
> [Here](https://github.com/FasterDecoding/Medusa/tree/sparse_tree/llm_judge)

This link seems broken?
