### ISSUE TITLE
name not exist "from medusa.model.medusa_choices import medusa_choices"

### ISSUE THREAD

**Issue by JianbangZ** [FasterDecoding/Medusa#48]
L#25 of llm_judge/gen_model_answer_medusa.py

**Comment by leeyeehoo** [comment]
Yes, I gonna fix it... before that you can try `from medusa.model.medusa_choices import mc_sim_7b_63`

**Comment by JianbangZ** [comment]
> Yes, I gonna fix it... before that you can try `from medusa.model.medusa_choices import mc_sim_7b_63`

Yah, I did. I hardcoded to ms_sim_7b_63 in order to run. I know this is a sparse tree implementation, can we still use non sparse manner like the old way medusa_choices=[1,7,6]?

**Comment by leeyeehoo** [comment]
Use the converter:
```
import itertools

def convert_medusa_choices(old_medusa_choices = [1, 7, 6]):
    medusa_choices = []
    ranges = [range(n + 1) for n in old_medusa_choices[1:]]
    for i in range(len(old_medusa_choices) - 1):
        medusa_choices += [list(comb) for comb in list(itertools.product(*ranges[:i + 1]))]
    return medusa_choices
```

**Comment by ctlllll** [comment]
This thread seems to be quiet for a while. Let me close it for now, and feel free to reopen it :)
