### ISSUE TITLE
How to test latency between medusa & baseline

### ISSUE THREAD

**Issue by YixinSong-e** [FasterDecoding/Medusa#49]
Actually I don't fine the latency script.

**Comment by leeyeehoo** [comment]
[Here](https://github.com/FasterDecoding/Medusa/blob/main/llm_judge/gen_model_answer_medusa.py). I'll add the baseline latency script. If there is a bug check: #48 . I'll fix it soon :)

**Comment by leeyeehoo** [comment]
Well, maybe need extra 2-3 days to wrap things up since the server is down and I don't have the access to any GPU currently :(

**Comment by leeyeehoo** [comment]
I updated the `./llm_judge`, if you have further question or request feel free to reopen it!
