### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by someone13574** [FasterDecoding/Medusa#5]
It would be nice if the readme (or blog) included some of the common benchmarks which compare the quality of speculatively decoded inference vs the original model’s quality.

**Comment by leeyeehoo** [comment]
We use [MT Bench](https://github.com/lm-sys/FastChat/blob/main/fastchat/llm_judge/data/mt_bench/question.jsonl) from FastChat. The results are shown in [the blog Appendix](https://sites.google.com/view/medusa-llm#h.2yq1gf32dw1x). If the temperature is set to 0, it should be exactly the same output as the original model's greedy-decoding output as the demo shows. If you have further questions feel free to reopen the issue!

**Comment by someone13574** [comment]
Is there data on how the MT Bench score changes with changes in head count and for different model sizes? Or is benchmark performance most dominantly controlled by typical acceptance and other factors negligible?
