### ISSUE TITLE
Install the package with the console script ?

### ISSUE THREAD

**Issue by devrimcavusoglu** [FasterDecoding/Medusa#50]
Setuptools can inherently create a console script from the `pyproject.toml`, and users can use

```shell
medusa --model path/to/model
```
`medusa` as the CLI name may clash with other eariler CLIs for any other tools though, so I'd suggest to make the name of the CLI sth like `medusa-llm`.

**Comment by ctlllll** [comment]
Thanks for the suggestion! We currently don't have a plan to enable the CLI name as this is a more research-oriented project rather than a battle-test product :)
