### ISSUE TITLE
errors occurred when running simple_gradio_interface.py

### ISSUE THREAD

**Issue by MeWannaSleep** [FasterDecoding/Medusa#51]
I tried with the simple_gradio_interface.py,but to found 
![image](https://github.com/FasterDecoding/Medusa/assets/135443303/e635b3cb-2262-4af6-830d-d213d840f613)
I googled it ,and it says the operand doesn't support fp16
However having changing the dtype here,
![image](https://github.com/FasterDecoding/Medusa/assets/135443303/6414669b-6d20-46ef-861a-6ce38c576661)
gives me a new error
![image](https://github.com/FasterDecoding/Medusa/assets/135443303/f46dba1b-9494-4cde-804f-1470ab7e0b55)

**Comment by ctlllll** [comment]
Hi, I saw you removed the `device_map` argument, in this case, you may need to manually move the model to the GPU with `model.cuda()` or `model.to(your_device)`.

**Comment by MeWannaSleep** [comment]
@ctlllll  thx for your reply
