### ISSUE TITLE
Quesitons about the Performance

### ISSUE THREAD

**Issue by Adam1679** [FasterDecoding/Medusa#6]
1) Is the baseline in your graph using greedy decoding or beam search?
2) What is the performance of your decoding method in the evaluation dataset? How large is the performance regression?

**Comment by ctlllll** [comment]
Hey Adam,

1. The baseline is greedy decoding/sampling decoding, depending on the temperature configuration from the original [MT bench](https://github.com/lm-sys/FastChat/tree/main/fastchat/llm_judge). But you can think of it as greedy decoding, as the speeds are the same.
2. We have a [figure](https://sites.google.com/view/medusa-llm#h.ybsda3p1jr2) in the ablation study part of the blog, please check it out :)
