### ISSUE TITLE
AttributeError: 'LlamaForCausalLM' object has no attribute 'medusa_head'

### ISSUE THREAD

**Issue by blwaji** [FasterDecoding/Medusa#60]
![Snipaste_2023-11-01_11-00-21](https://github.com/FasterDecoding/Medusa/assets/125439330/66bdd94d-4c57-49db-8415-eb534a9b8149)

**Comment by leeyeehoo** [comment]
Did you fix it? Sorry for the late reply :)

**Comment by ctlllll** [comment]
This thread seems to be quiet for a while. Let me close it for now, and feel free to reopen it :)
