### ISSUE TITLE
Clarifications on Models + Batch Size

### ISSUE THREAD

**Issue by RonanKMcGovern** [FasterDecoding/Medusa#66]
Which models are supported?

Currently, is it only Vicuna models?
- Although any Llama 2 model could be trained as well, it's just that without the original dataset the heads will be a little weaker?
- Mistral cannot be trained as that architecture isn't supported? correct?

What batch size is supported?
- Just a batch size of 1 for now?
- Same for the TGI support - it will only work for a batch size of 1?

Would be great if this could be added to the model card. Also, linking some

**Comment by leeyeehoo** [comment]
Support for the Mistral-based models is added ([branch](https://github.com/FasterDecoding/Medusa/tree/v1.0-prerelease)). Batch size 1 yes. We will soon release the new models :) Feel free to report any issue you encounter and we will address those ASAP.

**Comment by RonanKMcGovern** [comment]
Does speculative inference work for batch size greater than one? Thanks

And, thanks, that's great on Mistral being available, will open up training openchat 3.5 too and get away from the non-commercial vicuna.

**Comment by leeyeehoo** [comment]
It should work with batch size > 1. We are trying to find a good inference lib for implementation since extending bs>1 on vanilla hugging face is kinda like rebuilding the wheel... If you have any suggestions feel free to discuss :)

**Comment by RonanKMcGovern** [comment]
Ok, cool. I need to get better at the intimate details, but here are some high level thoughts:
- TGI is faster than vLLM so to the extent supporting that is possible, that's probably good.
- vLLM would also be a good option as it has an openai style api which makes adoption easy.

Thanks for all the answers above btw, I'm keen to check out the Mistral model.

**Comment by leeyeehoo** [comment]
Thank you for providing good insights!
