### ISSUE TITLE
how did you construct the sparse tree architecture

### ISSUE THREAD

**Issue by pengfeiwu1999** [FasterDecoding/Medusa#67]
excuse me, I have a question about how you construct the sparse tree architecture(eg.the variable mc_sim_7b_63)???
thanks

**Comment by leeyeehoo** [comment]
Hi, check [this](https://github.com/FasterDecoding/Medusa/tree/v1.0-prerelease/medusa/eval) out

**Comment by ctlllll** [comment]
This thread seems to be quiet for a while. Let me close it for now, and feel free to reopen it :)
