### ISSUE TITLE
About changing LLM from LLAMA to LLAMA-2

### ISSUE THREAD

**Issue by dydrkfl06** [FasterDecoding/Medusa#68]
Thanks for sharing your great works.

We are doing reproduction of your works for research purpose, with changing models from LLAMA to LLAMA-2.
Training with LLAMA-2 works well and acceptable rate is also compatible, but we have errors in generation part raised by KV-caching part. 
I wonder you have conducted experiments on Llama-2 and if you have, do you mind sharing the KV-cache code?

Thanks for reading!

**Comment by leeyeehoo** [comment]
[V1.0](https://github.com/FasterDecoding/Medusa/tree/v1.0-prerelease) should be compatible with Llama-1/2 and Mistral. If you still encounter any issue, please share more details so that we can help you out :)

**Comment by ctlllll** [comment]
This thread seems to be quiet for a while. Let me close it for now, and feel free to reopen it :)
