### ISSUE TITLE
Add support for LoRA finetuning for LLaMA-65B

### ISSUE THREAD

**Issue by YingHH1** [FasterDecoding/Medusa#7]
Since there is no Vicuna-65B, is it possible to use LoRA to finetune the LLaMA-65B base model whilst simultaneously full-finetuning the Medusa heads?

**Comment by ctlllll** [comment]
Hi,

Definitely! It's a good idea to train such a model with native Medusa heads, we list it in our [Roadmap](https://github.com/FasterDecoding/Medusa/issues/3), welcome to submit a PR if you'd like to help with this :)
