### ISSUE TITLE
Medusa 1 and 2 speed up

### ISSUE THREAD

**Issue by LotuSrc** [FasterDecoding/Medusa#73]
The difference between Medusa-1 and Medusa-2 is just training strategy. Why the two methods can lead to different speed up?

**Comment by ctlllll** [comment]
Thanks for your interest! Yes, they are just different training strategies, but they lead to different prediction abilities of Medusa heads, i.e., in Medusa-2, the backbone model is trained together with Medusa heads, therefore improving Medusa heads' prediction, which can translate to better speedup.

**Comment by LotuSrc** [comment]
Thanks for your reply.
