### ISSUE TITLE
megatron-llm模型的支持

### ISSUE THREAD

**Issue by Jokoe66** [FasterDecoding/Medusa#8]
请问支持megatron-llm模型吗？迁移到megatron-llm有什么注意事项吗？

**Comment by leeyeehoo** [comment]
你好，目前只支持vicuna7/13/33b。可以refer我们的roadmap，如果有什么建议可以comment。谢谢！

**Comment by ctlllll** [comment]
如果想迁移到megatron进行训练，可以参考我们的[训练脚本](https://github.com/FasterDecoding/Medusa/blob/main/medusa/train/train.py)，改动的地方非常少，应该比较容易迁移。也欢迎提PR添加训练脚本~
